import {
  defineNuxtModule,
  addPlugin,
  addImports,
  addServerImports,
  addTypeTemplate,
  createResolver,
} from '@nuxt/kit'

export interface ModuleOptions {
  /**
   * Enable $zod injection and useZod() auto-import in the Nuxt app (client + SSR).
   * @default true
   */
  client?: boolean
  /**
   * Enable useZod() auto-import and the #nuxt-zod/server explicit import in Nitro.
   * @default true
   */
  server?: boolean
}

export default defineNuxtModule<ModuleOptions>({
  meta: {
    name: 'nuxt-zod',
    configKey: 'nuxtZod',
    compatibility: { nuxt: '>=3.0.0' },
  },
  defaults: {
    client: true,
    server: true,
  },
  setup(options, nuxt) {
    const { resolve } = createResolver(import.meta.url)

    // ─── App-side (client + SSR) ──────────────────────────────────────────
    if (options.client !== false) {
      // Provides $zod on the NuxtApp instance
      addPlugin(resolve('./runtime/plugin'))

      // Auto-import useZod() in all app code (components, pages, composables)
      addImports({
        name: 'useZod',
        as: 'useZod',
        from: resolve('./runtime/composables/useZod'),
      })
    }

    // ─── Server-side (Nitro) ──────────────────────────────────────────────
    if (options.server !== false) {
      // Auto-import useZod() in Nitro routes, middleware, and server utils
      addServerImports([{
        name: 'useZod',
        as: 'useZod',
        from: resolve('./runtime/server/utils/useZod'),
      }])

      // Explicit import alias: import { z } from '#nuxt-zod/server'
      // Registered via nitro:config hook so Nitro's rollup plugin resolves it correctly
      nuxt.hook('nitro:config', (nitroConfig) => {
        nitroConfig.virtual ||= {}
        nitroConfig.virtual['#nuxt-zod/server'] = `export { z } from 'zod'`
      })
    }

    // ─── TypeScript augmentation ──────────────────────────────────────────
    addTypeTemplate({
      filename: 'types/nuxt-zod.d.ts',
      getContents: () => `// Auto-generated by nuxt-zod
import type { z } from 'zod'

declare module '#app' {
  interface NuxtApp {
    $zod: typeof z
  }
}

declare module 'vue' {
  interface ComponentCustomProperties {
    $zod: typeof z
  }
}

declare module '#nuxt-zod/server' {
  export { z } from 'zod'
}

export {}
`,
    })

    // ─── Vite: pre-bundle zod for faster dev HMR and cold start ──────────
    nuxt.options.vite.optimizeDeps ||= {}
    nuxt.options.vite.optimizeDeps.include ||= []
    if (!nuxt.options.vite.optimizeDeps.include.includes('zod')) {
      nuxt.options.vite.optimizeDeps.include.push('zod')
    }
  },
})
